name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Run unit tests
      run: go test -v ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t labs-tape .
    
    - name: Run container
      run: |
        docker run -d -p 42113:42113 --name test-container labs-tape
        sleep 5  # Espera que el servidor inicie
        curl -X POST http://localhost:42113/api/v1/manifests \
          -H "Content-Type: application/json" \
          -d '{"metadata":{"name":"ci-test"},"spec":{"source":{"image":"alpine:latest"}}}'
