name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Download dependencies
        run: go mod download

      - name: Run unit tests and save report
        run: |
          mkdir -p reporte
          go test -v . > reporte/reporte-pruebas.txt

      - name: Upload test report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: reporte-pruebas
          path: reporte/reporte-pruebas.txt

  build-and-test-docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t mi-servidor-docker .

      - name: Run Docker container in background
        run: docker run -d -p 42113:42113 --name test-container mi-servidor-docker

      - name: Wait for server to start
        run: sleep 5

      - name: Test API endpoint with curl
        run: |
          curl -X POST http://localhost:42113/api/v1/manifests \
            -H "Content-Type: application/json" \
            -d '{"metadata":{"name":"ci-test"},"spec":{"source":{"image":"alpine:latest"}}}'

      - name: Stop and remove container
        run: |
          docker stop test-container
          docker rm test-container

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Docker image
        run: docker tag mi-servidor-docker ${{ secrets.DOCKER_USERNAME }}/mi-servidor-docker:latest

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mi-servidor-docker:latest
